### ISSUE TITLE
Austrasse Distance failure

### ISSUE THREAD

**Issue by aarthykc** [ingalls/pt2itp#100]
While attempting to load Liechtenstein, I ran into a couple of errors, the one I paid close attention to are the ones with the Distance Failed:
`DIST FAIL - 1.19km - returned: 9.523064,47.131334|11 Austrasse|9.522526,47.120686`

#### The problem:
The two Austrasse streets are in close proximity to each other so when trying to look them up, with reverse geocoding in the `test mode` there's a distance failure.

#### Solution...?
To further dig in I tried: 
1. I tried to recreate the test case [here](https://github.com/mapbox/carmen/commit/fcebb2643bec6a41be964d2d1d2978d2cef2bb90), where the result I get back is the first index. 

2. Per chat with @sbma44, I tried loading the database locally in QGIS and looked at whether the `address_cluster`is contained within the `network_cluster` entirely. 

I was looking at the buffer, here's what I found: 

![image](https://cloud.githubusercontent.com/assets/10141319/26476130/5bb08dfc-4171-11e7-9690-33b323423958.png)
_Where the network_cluster ends for the first Austrasse street_

![image](https://cloud.githubusercontent.com/assets/10141319/26476165/aeb212aa-4171-11e7-9939-81415c0413e7.png)
_This is the position of the second Austrasse, it's completely outside the network_cluster buffer of the first_ 

@ingalls, @sbma44 I wonder if it's because of the `0.1` buffer change from before, would love to hear any ideas you have ?

**Comment by sbma44** [comment]
Hmm I'm not 100% on this but I think this might be the `ST_Contains` vs `ST_Intersects` thing I mentioned in chat. Can you edit the properties to filter this down to things with relevant named? Just double-click the layer in QGIS and edit it like:

![image](https://cloud.githubusercontent.com/assets/31717/26477158/a3d34a0a-4191-11e7-9e42-7f2283e512ef.png)

It might also be helpful to make the `network_cluster` somewhat transparent and to use the 
![image](https://cloud.githubusercontent.com/assets/31717/26477164/b2c66e0c-4191-11e7-8de4-4cb662996842.png) tool to highlight one of the `address_cluster` items so it's easier to see where one begins or ends (I'm sure there's a way to make them different colors in the QGIS style tab but idk how offhand).

**Comment by aarthykc** [comment]
@sbma44 fixed this, not seeing these errors anymore !
