### ISSUE TITLE
address cluster adoption

### ISSUE THREAD

**Issue by sbma44** [ingalls/pt2itp#116]
I've dropped some notes on this in https://github.com/ingalls/pt2itp/issues/97 but it's worth breaking out into its own ticket.

pt2itp creates address clusters by grouping sets of adjacent points. It then assigns these address clusters to network clusters based on spatial and name-matching heuristics. In some cases this results in situations like the following:

![image](https://user-images.githubusercontent.com/31717/27551019-d0029a8a-5a6f-11e7-9e05-10f4fb914c25.png)

Here the blue outline around the black points on the right signifies a match to the network cluster. As you can see, there is an identically-named set of address points that should be part of the matched address cluster.

Tweaking the address cluster creation process is a recipe for tears: there's no perfect set of spatial threshold settings. However, the successful link between the network and address clusters should allow us to identify identically-named points along the network cluster and add them to the assigned address cluster. I believe that [this query](https://github.com/ingalls/pt2itp/issues/97#issuecomment-305921577) needs to be added to cluster.js. However the bigger issue might be the complexity of the operation -- I think a test case is called for.

**Comment by sbma44** [comment]
renaming from `orphan` to `adoptee` etc bc Nick already uses `orphan` in map.js for something else 😞

**Comment by sbma44** [comment]
This is implemented in #119 and seems to work fine. Maybe... too well? I'm not seeing any `NOT MATCHED TO NETWORK` errors at all. And some of the matches are clearly wrong:

### Kitsarööpa Tee => Ehitajate Tee (24.67180,59.37644)
in this case `Ehitajate` is being matched correctly to a correctly-named network segment, but the cluster is _also_ being assigned to `Kitsarööpa`.
![image](https://user-images.githubusercontent.com/31717/27612062-c3607150-5b62-11e7-9ed5-c9e12c85973e.png)

### Rauakooli Tee => Akadeemia Tee (24.66379,59.39290)
another example -- all network segments here are linked to the same address cluster
![image](https://user-images.githubusercontent.com/31717/27612146-360d7a86-5b63-11e7-8f50-8f0a1c577550.png)

not sure whether the adoption query is causing this to happen or if something else is going on. next steps:

1. rerun master
2. dump db
3. run adoptee query
4. compare, determine answer to above question

**Comment by sbma44** [comment]
I've confirmed that both of these misassignments occur in both master and my branch. Looks to me like this is unrelated to the adoption query. I'll need to have a closer look at the linker behavior to be 100% here, but with the diff in hand I might also have a look for specific clusters that *are* affected by the adoption query.

**Comment by sbma44** [comment]
I created a QGIS view that shows only the address clusters that were revised by the adoption code. After manual review of many of them, I feel good about this change. Here's an example of what were previously two disparate clusters that are combined by the query.

![image](https://user-images.githubusercontent.com/31717/27654322-e4c52216-5c0f-11e7-9efb-6eeb896f3d3d.png)

Moving to request review in the PR.

**Comment by ingalls** [comment]
Fixed! Thanks a ton, this is amazing, the viz was also fantastic!!

**Comment by sbma44** [comment]
This was merged and subsequently optimized with a couple of indexes.
