### ISSUE TITLE
orphan join on NULL?

### ISSUE THREAD

**Issue by sbma44** [ingalls/pt2itp#117]
@ingalls ran across this today: https://github.com/ingalls/pt2itp/blob/bce4128abc52c0e9dd69af7a918fc1b18f900ee3/lib/map.js#L400

seems like an odd join given that it's restricted to NULL only, yeah? I think this probably works fine since you're just looking for the `count()` but I thought I'd flag.

**Comment by ingalls** [comment]
Yes this join is intentionally on null as it is the fastest way to do a cross join on the network table to find all the orphans. It is done 2 times, the first time with a `count(*)` and the second time with a cursor on https://github.com/ingalls/pt2itp/blob/bce4128abc52c0e9dd69af7a918fc1b18f900ee3/lib/map.js#L410
