### ISSUE TITLE
Titlecase & Cardinals

### ISSUE THREAD

**Issue by ingalls** [ingalls/pt2itp#146]
Input: `3134 D ST NE`

Current Incorrect Output: `3134 D St Ne`
Expected Output: `3134 D St NE`

Also Applies to
```
Northeast => NE
Northwest => NW
Southeast => SE
Southwest => SW
```

cc/ @sbma44

**Comment by sbma44** [comment]
on it

**Comment by ingalls** [comment]
Tracking Ref: https://github.com/ingalls/pt2itp/pull/161
