### ISSUE TITLE
US DC Synonyms

### ISSUE THREAD

**Issue by ingalls** [ingalls/pt2itp#165]
`Haley Place SW,Haley Place Southwest`

The synonym checker should use tokens to compare the network/address text to choose if a synonym is added to reduce the index side.

cc/ @sbma44 @aaaandrea

**Comment by sbma44** [comment]
just for cardinality? more?

fwiw this might be a good place to do this -- I believe that the tokenized versions of the feature text should be available https://github.com/ingalls/pt2itp/blob/362b8fadff7a168d151b5c8da984009be04a5e11/lib/label/titlecase.js#L119-L123

**Comment by ingalls** [comment]
I just saw the cardinality while browsing through but I suspect it will apply to all tokens

**Comment by ingalls** [comment]
To add to the Synonym issues:

`Fourth St vs 4th Street`

^ This problem is widespread and makes an absolute mess of clustering in cities with grid based street names
