### ISSUE TITLE
[proposal] supporting multiple names for network clusters

### ISSUE THREAD

**Issue by sbma44** [ingalls/pt2itp#180]
consider this real-world scenario:

![image](https://user-images.githubusercontent.com/31717/30174151-17b726a2-93c8-11e7-8661-a470da42de3c.png)

The network line in question has both names assigned to it in our source data -- this assignment can be made... theoretically.

So what if we just added multiple names to the network_cluster and ran each one through `linker`? It'd work fine for this:

![image](https://user-images.githubusercontent.com/31717/30180393-bd167804-93dd-11e7-8f3a-23693419f160.png)

What do we do with the network_cluster when the alternate name(s) only exist on part of the road? This is pretty common. Breaking it into three individual `network_cluster`s is an obvious strategy. And that would work sometimes, like here:
![image](https://user-images.githubusercontent.com/31717/30180485-0a7d0bd0-93de-11e7-9ce4-c5eb68fe5dfd.png)

But we have to consider cases when the points are labeled in a manner that doesn't totally correspond to where the network data says it starts and ends. This is also pretty common:
![image](https://user-images.githubusercontent.com/31717/30180660-9dd812f8-93de-11e7-90be-b4583b4b9fe5.png)
![image](https://user-images.githubusercontent.com/31717/30180675-ac3c6844-93de-11e7-99fe-6319507b2297.png)

The bottom case is especially bad, because the address cluster would be assigned to one of the `Rt 10` segments but not all three, producing obviously bad interpolation output.

----------

So what do we do? I think at ingestion we should add a new `network` table row for each synonym attached to a road segment. Clustering proceeds as normal, producing overlapping road geometry that can be assigned to whichever address cluster matches its name.

What happens in the third case above? Well, two options. In the simplest implementation, we just get bad interpolation data for the central segment.

But! I think it would be preferable to store original network segment IDs (e.g. OSM IDs) in the `network` table and then pass these through to `network_cluster` with an `ARRAY_AGG(source_id) AS source_ids`. We then select groups of `network_cluster`s where `a.source_idd && b.source_idd AND ST_Intersects(a.buffer, b.buffer)` and consider whether to merge them. Here's some pseudocode that I am pretty sure will contain bugs:

```
output_segments = [ longest(network_segments) ]
remaining_segments = network_segments - longest(network_segments)
for seg in remaining_segments:

  # look for coextensive segments & collapse together
  merged_with_twin = false
  for o in output_segments:
    if o.source_ids == seg.source_ids:
      o.add_synonym(seg.name)
      o.address.merge_points(seg.address.points)
      merged_with_twin = true

  # look for short segments with big address clusters -- give the address cluster to the bigger segment
  # where appropriate
  if not merged_with_twin and seg.address != NULL:
    for o in output_segments: # this should maybe examine all segments but in practice I think this would be fine
      if seg.address.extent_is_obviously_better_matched_to(o):
        o.add_synonym(seg.name)
        o.address.merge_points(seg.address.points) # need to handle the o.address == NULL case
        continue

  # fall back to emitting this as its own network_cluster
  output_segments.push(seg)

# output segments get put in network_cluster, the others get deleted, and the process continues

```

This is perhaps too much trouble for a rare case. But I think the first part of this -- splitting network segments into multiple copies in `network` -- is doable with minimal effort.

cc @ingalls, oh man do I need to talk this through with you

**Comment by boblannon** [comment]
you can do string matching across arrays of strings in postgres, if it helps.

you could have a where clause like:

```
WHERE address_cluster.name ILIKE ANY(REGEXP_SPLIT_TO_ARRAY(network_cluster.name, '/'))
```

**Comment by sbma44** [comment]
Interesting! Two things though:
- the text matching algorithm in linker is implemented in JS--it would be a bear to do in SQL
- it's really the not perfectly matched geometry that's the problem rather than the many to many text comparison. So I think splitting the geom is going to be essential, which poses thorny problems for reducing the geonetry later but makes the existing text matching usable without modification

**Comment by sbma44** [comment]
The first part of this code is now in #182. It successfully generated distinct `network` rows for each alternate name of a feature and populates the `source_ids` column of the `network_cluster` table with an array of the `network` IDs used to compose that segment. I think this gives us the basic tools necessary to support multiple labels. But more work is needed, as well as general feedback on the approach.

Current to-do list:
- `./load` currently fails to emit any results (though `network_cluster` to `address_cluster` assignments _are_ made). I haven't debugged why yet, though I'd bet on the `MultiLineStringZ` transition of `network_cluster`
- does `ST_ClusterWithin()` respect z-coordinates? if so, adjustments might have to be made, as I'm storing the `network` ID there a la @ingalls' `address` method
- a fixture-based test probably reflects some of this functionality, but a proper unit test is definitely called for
- the big remaining question is how and whether to collapse network clusters together. I have not yet written a query to systematically analyze the number of `network_cluster`s with completely identical source segments, but examination in QGIS makes it look like perfect identity will be somewhat rare. This is in part due to my inclusion of TIGER metadata in minjur.js, which creates lots of extra network clusters. In addition to the ideas embodied in the above pseudocode we're going to want to also use an adjusted `linker.js` to unify segments.

**Comment by sbma44** [comment]
OK, tests are passing on the PR. Addressing the above bullets:
- load now works
- @ingalls assures me that he's dug into the code with Dane and `ST_ClusterWithin()` is not affected by z coordinates for points -- there's no particular reason to think it would apply to linestrings, so let's go with it for now
- I had to revamp a ton of additional tests to get things passing and now feel pretty confident that coverage of the new splitting functionality is okay. I would write something for the specific combinations of tags that lead to duplicated geometry in `lib/map/osmium.js` (formerly `lib/map/minjur.js`), except I don't think those are firmed up yet. Call that a **@TODO**.
- I've had a chance to think about how merge strategies should work and talk it over with @ingalls. See below for the scenarios I want to support initially. Still thinking about how to iterate over the set of things that needs comparison, still feeling wary about race conditions. 

------

For the following, please assume that overlapping segments represent geometry with the same OSM ID.

For instance, in the following the 'a' & b' network_clusters share OSM network segments 2 and 3.
```
    1         2         3
aaaaaaaa  aaaaaaaa  aaaaaaaa
          bbbbbbbb  bbbbbbbb
```

# should merge network_clusters

## identical source segments
```
aaaaaaaaaa aaaaaaaaa aaaaaaa a    Main St
bbbbbbbbbb bbbbbbbbb bbbbbbb b    RT 50
```
## mismatch is small % of length
```
aaaaaaaaaa aaaaaaaaa aaaaaaa      Main St
bbbbbbbbbb bbbbbbbbb bbbbbbb b    RT 50
```

## strong text match, small overlap
```
           aaaaaaaaa              Main Street
bbbbbbbbbb bbbbbbbbb bbbbbbbbb    MAIN ST
```

# should change point ownership

## points span longer segment, name matches shorter segment
```
       bbbbbbbbb               Main st
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa    RT 50
B  B   BB   B    B     B   B B    Main st (addresses)
```

**Comment by sbma44** [comment]
I've been thinking about the above a bit more. Consider this additional case:

```
                bbbbbbbbb                  Main st
         aaaaaa aaaaaaaaa aaaaaaaaaaaaa    RT 50
         B  B   BB   B    B     B   B B    RT 50 (addresses)
```

Here, a `Main St` network_cluster exists but it has no address cluster assigned -- we have no idea what the numbering on it is. _Should we assume its numbering scheme is continuous with `RT 50`?_ The examples I've looked at so far imply the answer is yes but I'm not sure if I've looked at enough of them.

If the answer **is** yes then the `should change point ownership` case becomes identical, and both should just be merges.

**Comment by sbma44** [comment]
@mattficke delivered an example where this won't work: Vandalia IL. County Road 875 East is north of town, it’s N Kennedy blvd in town, and their address ranges are not consistent. So! We'll ignore the additional case and stick with address swapping for the last case.

**Comment by sbma44** [comment]
Working to implement the "substantial overlap" case. Here's the first one I looked at (around -80.35866,39.28882 in WV):

```
+-------------------+ 25th St
                  +-+ S 25th St
+----------------+    N 25th St
```

In this case, `25th St` and `N 25th St` could be collapsed together on the basis of shared length. I don't _think_ this is desirable.

**Comment by sbma44** [comment]
Had a look at optimizing the cluster collapsing query's 3 components and was surprised to see the `DELETE` being the most expensive:

```
                                                                            QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Update on address_cluster a1  (cost=401.82..409.88 rows=1 width=165) (actual time=0.027..0.027 rows=0 loops=1)
   InitPlan 1 (returns $0)
     ->  Index Scan using network_cluster_id_idx on network_cluster network_cluster_1  (cost=0.42..8.44 rows=1 width=4) (actual time=0.018..0.018 rows=1 loops=1)
           Index Cond: (id = 6391)
   ->  Nested Loop  (cost=393.39..401.44 rows=1 width=165) (actual time=0.025..0.025 rows=0 loops=1)
         ->  Index Scan using address_cluster_id_idx on address_cluster a1  (cost=0.42..8.44 rows=1 width=73) (actual time=0.024..0.024 rows=0 loops=1)
               Index Cond: ((id IS NOT NULL) AND (id = $0))
         ->  Subquery Scan on a2  (cost=392.96..392.99 rows=1 width=88) (never executed)
               ->  Aggregate  (cost=392.96..392.98 rows=1 width=32) (never executed)
                     ->  Nested Loop  (cost=8.86..16.90 rows=150424 width=452) (never executed)
                           ->  HashAggregate  (cost=8.44..8.45 rows=1 width=4) (never executed)
                                 Group Key: network_cluster.address
                                 ->  Index Scan using network_cluster_address_idx on network_cluster  (cost=0.42..8.44 rows=1 width=4) (never executed)
                                       Index Cond: (address IS NOT NULL)
                                       Filter: (id = ANY ('{6391,25109}'::integer[]))
                           ->  Index Scan using address_cluster_id_idx on address_cluster  (cost=0.42..8.44 rows=1 width=456) (never executed)
                                 Index Cond: (id = network_cluster.address)
 Planning time: 0.374 ms
 Execution time: 0.127 ms
(19 rows)


                                                                            QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Delete on address_cluster  (cost=8.86..16.90 rows=150424 width=12) (actual time=32.769..32.769 rows=0 loops=1)
   ->  Nested Loop  (cost=8.86..16.90 rows=150424 width=12) (actual time=32.767..32.767 rows=0 loops=1)
         ->  HashAggregate  (cost=8.44..8.45 rows=1 width=10) (actual time=32.766..32.766 rows=0 loops=1)
               Group Key: network_cluster.address
               ->  Index Scan using network_cluster_address_idx on network_cluster  (cost=0.42..8.44 rows=1 width=10) (actual time=32.763..32.763 rows=0 loops=1)
                     Index Cond: (address IS NOT NULL)
                     Filter: (id = 25109)
                     Rows Removed by Filter: 40889
         ->  Index Scan using address_cluster_id_idx on address_cluster  (cost=0.42..8.44 rows=1 width=10) (never executed)
               Index Cond: (id = network_cluster.address)
 Planning time: 0.247 ms
 Execution time: 32.825 ms
(12 rows)

                                                                             QUERY PLAN
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Update on network_cluster n1  (cost=8.87..16.94 rows=1 width=1683) (actual time=0.105..0.105 rows=0 loops=1)
   ->  Nested Loop  (cost=8.87..16.94 rows=1 width=1683) (actual time=0.068..0.073 rows=1 loops=1)
         ->  Index Scan using network_cluster_id_idx on network_cluster n1  (cost=0.42..8.44 rows=1 width=1498) (actual time=0.017..0.019 rows=1 loops=1)
               Index Cond: (id = 6391)
         ->  Subquery Scan on na  (cost=8.45..8.47 rows=1 width=216) (actual time=0.043..0.045 rows=1 loops=1)
               ->  Aggregate  (cost=8.45..8.46 rows=1 width=96) (actual time=0.038..0.038 rows=1 loops=1)
                     ->  Index Scan using network_cluster_id_idx on network_cluster n2  (cost=0.42..8.44 rows=1 width=39) (actual time=0.008..0.008 rows=0 loops=1)
                           Index Cond: (id = 25109)
 Planning time: 0.215 ms
 Execution time: 0.178 ms
(10 rows)
```

Moving the `IS NOT NULL` check outside the subquery substantially improved the execution plan, but real-world benchmarks didn't budge:

```
WITHOUT OPTIMIZATION 346.10user 18.54system 11:12.29elapsed 54%CPU (0avgtext+0avgdata 114400maxresident)k
WITH OPTIMIZATION 343.35user 18.03system 11:14.09elapsed 53%CPU (0avgtext+0avgdata 111812maxresident)k
```

(note: these are times from invocation of `./load` to a `process.exit()` dropped into the collapse method where it would normally invoke its callback.)

I'm always wary of parallelized write SQL calls but decided to let pg-pool work some magic and indeed, this led to a substantial speedup:

```
WITH PARALLELIZATION (p=10) 347.29user 17.74system 5:52.51elapsed 103%CPU (0avgtext+0avgdata 109904maxresident)k
WITH PARALLELIZATION (p=20) 345.45user 18.02system 5:51.70elapsed 103%CPU (0avgtext+0avgdata 107684maxresident)k
```

I added some instrumentation and the dedupe operation takes about 55s for West Virginia. This is with only one of four dedupe steps implemented, but the remaining three should have much less activity.

Two obvious optimizations remain:
- batch queries prior to sending them to pool.query
- collect the information retrieved in the subqueries of `collapseNetworkClusters()` in the initial upstream query and pass them into the method

Of these, 1 should definitely be tried first. But I'm pausing here; I think 1 or 2 minutes is an acceptable performance hit for this.

**Comment by sbma44** [comment]
Seeing lots of real-world examples of what I mentioned [here](https://github.com/ingalls/pt2itp/issues/180#issuecomment-331995998)

![image](https://user-images.githubusercontent.com/31717/30832574-88b5cc50-a219-11e7-8625-c8bf8bfa130a.png)
```
{"id":20,"source_ids":[15561074,15563812],"_text":"10th Avenue","network_length":1.127811628053352}
    {"id":30568,"source_ids":[15561074],"_text":"East 10th Avenue","network_length":1.0545962757884801,"overlapLength":1.0545962757884801}
    {"id":73726,"source_ids":[15563812],"_text":"West 10th Avenue","network_length":0.07321535226487201,"overlapLength":0.07321535226487201}
```

This is 93% overlap -- below the 95% that I pulled out of thin air -- but it's going to be important to evaluate the specific merges that are performed over the 95 threshold to make sure it's safe.

It's possible that what's needed here is combining this with the `strong text match` case -- I was already planning on sharing a codepath, but perhaps the overlap should be aware of cases with high text similarity except for token dissimilarity. That should be detectable. But spitting out the actual merges is the next step.

**Comment by sbma44** [comment]
shipped in https://github.com/ingalls/pt2itp/issues/72
