### ISSUE TITLE
TitleCase Behavior

### ISSUE THREAD

**Issue by ingalls** [ingalls/pt2itp#237]
Proposal:

Move Titlecase behavior out of the current `label` system and into it's own `post` module. While retaining label for it's current behavior of choosing which label to put first/last address vs. text.

Discovered Issue:
The NameNetwork function which finds and autonames unnamed street segments - copies the exact address street text to the network.

The label module _does not_ title case when the address/network is the same - which is always the case for autonamed segements.

This results in our API returning things like:
`123 main st northeast`
`123 MAIN ST NORTHEAST`.

A second thing to consider is that many of our addresses are abbreviated  to 2 letter codes which are sub-optimal for our api. Do we want to add "preferred: true" to our geocoder-abbr module for abbreviations and auto-expand where there are no conflicts?

IE: ` 6010 53rd av s` should probably be ` 6010 53rd Ave S` or `6010 53rd Avenue S`

cc/ @sbma44

**Comment by sbma44** [comment]
OK -- I've got this reloaded into my head but am now less convinced that it's a good idea. Right now we don't apply titlecasing when lowercased, diacritic-stripped versions of the network and address text are identical -- rather, we choose the one with more case changes, assuming it contains more information. So for instance `Québec` and `QUEBEC` would hit this codepath and `Québec` would win.

I get that the autoname scenario produces undesirable results as expressed above. But it seems like the right solution there is to apply titlecasing at the autoname step in cases where `numCaseChanges(text) == 0`.

What I don't see: how do we retain source data richness if titlecasing is moved to a post script? I think the implicit hypothesis in this ticket is that we should apply a uniform titlecasing transformation to everything, but I think that's probably not true.

**Comment by sbma44** [comment]
OK -- we will definitely have to talk this through tmw, since it represents not only a change from the plan proposed in the original ticket but an expansion of the behavior you object to, @ingalls. But I did a quick (totally untested, probably syntax-error-filled) sketch of what I'm proposing:

https://github.com/ingalls/pt2itp/compare/FreeRadicals...FreeRadicalsSorryNick?expand=1
