### ISSUE TITLE
Cross Match Reporting Error

### ISSUE THREAD

**Issue by ingalls** [ingalls/pt2itp#431]
Attempting to build Ontario, Canada currently results in the `Cross Matching Data` step hanging, preventing processing from finishing.

Based on the logs this appear to be an off by one error

![Screenshot from 2019-03-19 10-54-57](https://user-images.githubusercontent.com/1297009/54629776-7fd68c80-4a35-11e9-90ae-510f84b47dbc.png)

According to HTOP all of the child processes have terminated but the controller does not believe that all the data has been processed and continues to wait for further results.

**Comment by ingalls** [comment]
```
AddrNum_it AddrNum
8910001 8905099
```

**Comment by boblannon** [comment]
just hit the same issue when testing `ru mow` build
