### ISSUE TITLE
analyze tests failing locally

### ISSUE THREAD

**Issue by lizziegooding** [ingalls/pt2itp#453]
## Context

While running tests, I noticed that the tests in analyze.test.js consistently fail locally (even on master), but pass just fine on CI. I haven't investigated further, but I'm guessing this may have to do with the fact that I'm running on OS X or that we're using a dependency/version of a dependency on CI that isn't captured in the project's package.json/Cargo.toml.

The tests that are failing:
- `25 no results returned from network_unigrams. query was "SELECT * FROM network_unigrams;"`
- `26 SQL table network_unigrams has expected values`
- `33 SQL table unigram_comparison has expected values`
- `34 network unigram output is as expected`
- `35 address unigram output is as expected`

## Next steps

I don't have time to look into these in the next day or two, but wanted to note as something we should fix/in case anyone else runs into this.

- [ ] investigate why these tests are failing
- [ ] cut a PR

cc @ingalls @samely @boblannon

**Comment by boblannon** [comment]
@lizziegooding i think we're probably good to retire the `analyze` stuff.  I'm confident that no one's using it these days, so don't let it block your work.
