### ISSUE TITLE
reenable alt name support in lib/index

### ISSUE THREAD

**Issue by sbma44** [ingalls/pt2itp#72]
Right now `feat.properties.street` _can_ be an array of alt names -- but when it is, only the first is used. I'm unsure how deep this 🐇 🕳  will go, but @ingalls says a good place to start is with tests demonstrating that street alt names make it through the `index` script.

**Comment by ingalls** [comment]
This is going to be one of the more ambitious quests I think

**Comment by sbma44** [comment]
this shipped in https://github.com/ingalls/pt2itp/pull/182
