### ISSUE TITLE
remove getNames?

### ISSUE THREAD

**Issue by sbma44** [ingalls/pt2itp#94]
@ingalls does this do anything anymore? https://github.com/ingalls/pt2itp/blob/e4989f558ddcdafe7a5e6015b9e5b339baeba6f6/lib/map.js#L232-L247

Seems like `getNames()` could be taken out of the logic entirely.

**Comment by ingalls** [comment]
Good eye, yeah this was previously passed to the `freq` function to do the frequency calculation. Since I ripped that out and replaced it with the dramatically simpler & also much better lev distance it can go.
