### ISSUE TITLE
st_contains instead of st_intersects?

### ISSUE THREAD

**Issue by sbma44** [ingalls/pt2itp#95]
@ingalls I've been trying to puzzle through why some addresses don't get assigned properly, even when the underlying network data supports it. Here's a failure case in the Estonian subdistrict of [Kopli](https://en.wikipedia.org/wiki/Kopli), on a road of the same name:

![image](https://cloud.githubusercontent.com/assets/31717/26333414/7e2f078e-3f2b-11e7-9ab9-7c1162ce1b61.png)

This geometry contains a similarly named nested cluster (`Kopliranna`), but I think the actual problem is the use of `ST_Contains` [here](https://github.com/ingalls/pt2itp/blob/e4989f558ddcdafe7a5e6015b9e5b339baeba6f6/lib/cluster.js#L112). I know you've played with the buffer a ton on these things -- is ST_Intersects an option, or did you try that and discard it?

**Comment by ingalls** [comment]
Ah also a good call. To date I've been working with countries that have very good network coverage so haven't run into a case that I was debugging where the addresses fell outside the buffer. Switching to `ST_Intersects` sounds like a great idea.

**Comment by sbma44** [comment]
this was merged
