### ISSUE TITLE
adjust linker comparison

### ISSUE THREAD

**Issue by sbma44** [ingalls/pt2itp#97]
right now match percentage is calculated like so:

```js
let score = 100 - (((2 * levScore) / (address.text.length + street.text.length)) * 100)
```

We insist on this value being > 40% for a match, but I think this is incorrect, and has a particularly negative effect on short strings. Consider the match between `Lõo` and `Lõo Tn` (nee `Lõo Tänav`). Levenshtein distance 3, `score` value of 33.3.

Here are some real-life examples of missed assignments -- note how large a percentage of the string the token tends to be:

```
6 Lõo Tänav|24.492061,58.414735
12 Eha Tänav|26.515548,59.505119
7a Pae Tänav|25.19637,59.379563
2 Maisimäe Põik|25.059272,59.013705
21 Puiestee Tänav|26.397305,58.744343
4 Elupuu Põik|24.678222,59.242531
4 Uus Tänav|26.070964,58.937886
59 Mai Tänav|24.540118,58.367729
37 Mai Tänav|24.535948,58.370571
11 Narva Maantee|24.763742,59.437592
2 Linnuraja Põik|26.800526,58.375394
13c Uus Tänav|26.737669,58.381942
10 Jõe Tänav|24.745986,59.177765
12 Mäe Tänav|25.198446,58.091204
18 Uus Tänav|24.810747,58.773088
3 Eriku Tee|24.751844,59.276265
16b Lasti Tee|24.941017,59.491875
4a Tui Tänav|24.516256,58.385936
26 Aia Tänav|22.474859,58.25166
9 Aia Tänav|25.099775,58.621157
4 Mäe Tänav|24.364578,58.512065
24 Jalakanurme Tee|24.539705,58.47026
148 Narva Maantee|24.826009,59.447344
2 Lao Tänav|24.766314,59.023915
46 Soo Tänav|24.733545,59.446872
16 ööKulli Tee|27.036634,57.84388
9 Nõlvaku Tänav|26.777058,58.374431
6 Pilistvere Tee|25.887174,58.642321
12 Niidu Tee|26.056847,59.374802
6 Käo Tänav|25.97863,58.662403
```

Tokens _can_ contain high value data: an `Ave` vs `St` mismatch should be noted. But omitting a token shouldn't be considered as big of a deal. I suppose we could customize an edit distance metric that prioritizes substitution over deletion, but I think a more efficient approach might be a weighted distance: let's calculate the current score but also one that's based on strings with all tokens removed, then calculate an average score weighted toward the latter. This should be simpler to implement, easier to tune and will require minimal modifications to the code.

**Comment by sbma44** [comment]
This has helped -- a sample of 20 random errors after rerunning (19 listed here; one was a dupe of the same street)

## bad OSM data
2 Tuule Tänav|25.576855,58.342427 - tagged as proposed in OSM
8 Allika Tänav|26.809785,58.317971 - tagged as proposed in OSM
14 Vainu Tee|24.880788,59.541803 - not in OSM
1 Orava Tee|24.610357,59.23399 - tagged as proposed
2 Kingu Tänav|25.192495,59.379091 - not mapped in OSM
8 Ringi Tee|24.586323,58.270807 - not mapped in OSM
5 Oja Tänav|27.343213,58.008438 - present in OSM. investigate.
21 Hõreda Tee|24.23109,59.37881 - not named in OSM
25 Kähriku Tee|24.823111,59.523061 - tagged as highway=construction
7 Rehemäe Tee|23.620582,58.953945 - tagged as proposed in OSM
3 Leandri Tee|25.05032,59.013649 - unnamed service road on OSM
9 Vaablase Tänav|24.772396,59.179747 - tagged as proposed road on OSM

## all-token street names
* 15 Puiestee Tänav|26.431563,59.36432 - this is legit in OSM. investigate.
`Puistee` is being tokenized to `Pst`. So... Avenue Street?
* 45 Oja Tänav|24.524916,58.392079 - present in OSM. investigate. Oja gets collapsed to "O". So: "O Tn" versus "O" -- and tokenless versions don't help bec
* 83 Puiestee Tänav|26.737289,58.385498 - present in OSM. investigate.
Same issue. All-token name.

## address clusters that are too small/should be combined
* 3a Lihula Maantee|24.360215,58.415715 - tagged as lihula mnt -- check tokens. investigate.
multiple address clusters that should be assigned to the same network. currently impossible. there's also nesting of identically-named network clusters, though.
ause they're empty. no hope here.
* 18 Nuudi Tee|24.996853,59.485428 - present in OSM. investigate.
multiple address clusters that belong to the same network cluster.
* 38 Narva Maantee|24.772275,59.438028 - present in OSM. check tokens. investigate.
multiple address clusters. but also: network cluster is not getting joined successfully.

## other
* 11 Nõlvaku Tänav|26.776646,58.374001 - present in OSM. investigate.
unclear why these aren't being assigned
![image](https://cloud.githubusercontent.com/assets/31717/26432533/57f7f38c-40ca-11e7-9c9a-35c47d5f606b.png)

I have some ideas about the all-token street name issue, though they're hacky (basically: it's possible to detect this case. when it happens, check for one string being a subset of the other).

The address cluster issue is trickier. @ingalls can we just make the spatial clustering more aggressive?

**Comment by sbma44** [comment]
# debugging notes

Here's how I have been approaching this.

## run the pt2itp test mode
@ingalls has documented this / it's baked into carmen-indexer's code

## examine the ratio of errors in the output file
- `dist fail`s are potentially serious and imply that something is going wrong with indexing.
- `text mismatch`es may be worth ignoring if you understand why they are occurring (do OSM and OA use different abbreviation schemes?)
- `not matched to network` is indicative of either a) bad/incomplete data or b) pt2itp bugs. The ratio between A and B should be examined. There is plenty of room for improvement, but once data errors predominate it may be time to ship.

## sampling errors
I do something like `grep NETWORK out.err | shuf | head -n 20` | cut -d '|' -f2,3`. I then take the results to a ticket or text editor.

I also export the database to my local machine. You can alternately plan to start your morecs with port 5432 exposed, but I tend to start them with port 4000 and then can't change it. We could modify morecs again. For now, I suggest doing this on your machine:

```sh
# install ngrok -- probably `brew install ngrok`?
ngrok tcp 8080 # then note the port number it gives you
<<then in a different tab>>
nc -l 8080 | gunzip > db.pgsql
```

on the morecs:
```sh
apt-get install -y netcat
pg_dump -U postgres mbpl_cc_address_both | gzip | nc 0.tcp.ngrok.io $NGROK_PORT_NUMBER
```

Note that netcat behaves weirdly with docker networking / doesn't seem to notice pipe ends correctly. So you will want to `tail` the pgsql file to see if it's complete, then ctrl+c out of the various programs listed here.

To load the pgdump: `psql -q -t -U postgres < db.pgsql`

Now you can examine it in QGIS. But first:

## check OSM
Take the lon/lat of the failure and paste it into the hashbang at openstreetmap.org. I find this to be more reliable than the style at geojson.io, particularly since you can hit "edit" to see more data, like proposed roads. If the road is not there/unnamed/tagged as `construction` or `proposed`, congratulations! pt2itp is behaving itself. If it _is_ there and seems to be in order...

## examine the shape of network and address_cluster in the database
you can paste the coordinates into the bottom of the QGIS UI. filter each layer down to the feature by adding a filter like `_text ILIKE '%whateverthestreetnameis%'` in the layer properties. Click around, bug @ingalls, etc.

**Comment by aarthykc** [comment]
Thanks for the debugging notes @sbma44 ! This is great 👌

**Comment by sbma44** [comment]
continuing to hammer on this... the orphan cluster issue is up next, but there was a tokenless bug that needed squishing first by the numbers. I also opened the filter on `construction` and `proposed` ways. rerunning in a sec...

# pt2itp failures

## 1 Kõrgepõllu Põik|25.64941,58.380261
https://www.openstreetmap.org/#map=17/58.380261/25.64941
`highway=residential` -- orphan cluster

## 2 Oja Tänav|24.611649,59.42962
https://www.openstreetmap.org/#map=17/59.42962/24.611649
the all-token case's substring comparison was running on post-tokenization `text` instead of `_text`. this was done because `_text` still has diacritics, but it resulted in problems (like the substring test just being for the character `o`, as was happening in this case). firmed this up to make the substring comparison work on a lowercase & de-diacritic-ized version of `_text`.

## 7 Oja Tänav|25.973076,59.572787
https://www.openstreetmap.org/#map=17/59.572787/25.973076
same substring problem as ^^^

## 24 Puiestee Tänav|26.721203,58.392469
https://www.openstreetmap.org/#map=17/58.392469/26.721203
`highway=trunk` -- same substring problem as ^^^

## 3 Oja Tänav|27.342976,58.009002
https://www.openstreetmap.org/#map=17/58.009002/27.342976
`highway=residential` -- same substring problem as ^^^

# bad OSM data

## 1 Soinaste Tänav|26.698428,58.363508
https://www.openstreetmap.org/#map=17/58.363508/26.698428
`highway=construction`

## 18 Mõisahärra Tänav|26.740213,58.406419
https://www.openstreetmap.org/#map=17/58.406419/26.740213
`highway=footway` (google geocodes it, present on map/satellite)

## 3 Nõmme Tee|24.200929,59.394757
https://www.openstreetmap.org/#map=17/59.394757/24.200929
Not mapped

## 8 Erminurme Tee|26.749949,58.397644
https://www.openstreetmap.org/#map=17/58.397644/26.749949
`highway=proposed` (google geocodes it, tho not on map/satellite)

## 2 Uusna Tee|24.787269,59.322936
https://www.openstreetmap.org/#map=17/59.322936/24.787269
`highway=proposed` (google geocodes it, tho not on map/satellite)

## 4 Tormi Tee|25.449924,59.484288
https://www.openstreetmap.org/#map=17/59.484288/25.449924
`highway=proposed` (google geocodes it, tho not on map/satellite)

## 7 Sälu Tänav|24.944608,59.460396
https://www.openstreetmap.org/#map=17/59.460396/24.944608
Not mapped

## 15r Hoidla Tee|25.003398,59.505298
https://www.openstreetmap.org/#map=17/59.505298/25.003398
Not mapped (but probably `highway=service`)

## 7 Rehe Põik|24.34016,59.420066
https://www.openstreetmap.org/#map=17/59.420066/24.34016
`highway=construction` -- google geocodes it

## 12 Jõenurme Tänav|24.762492,58.988376
https://www.openstreetmap.org/#map=17/58.988376/24.762492
`highway=proposed`

## 2 Rahvamaja Tee|25.138877,59.46678
https://www.openstreetmap.org/#map=17/59.46678/25.138877
not mapped

## 8 Kaldaveere Tee|24.234379,59.38141
https://www.openstreetmap.org/#map=17/59.38141/24.234379
not mapped

## 19 Kullamäe Tee|25.322605,59.495813
https://www.openstreetmap.org/#map=17/59.495813/25.322605
not mapped -- there are some ways under construction around here

## 3 Lõuna Tänav|26.449724,58.235808
https://www.openstreetmap.org/#map=17/58.235808/26.449724
not mapped

## 89 Leivajõe Tee|24.993883,59.368776
https://www.openstreetmap.org/#map=17/59.368776/24.993883
`highway=proposed`

**Comment by sbma44** [comment]
Looks like all-token mode still needs some love before I tackle orphan address clusters. I'm going to write a linker test case based on the IDs captured below to figure out what's going on.

# orphaned address clusters

## 28 Paide Maantee|24.645742,58.393858|https://www.openstreetmap.org/#map=16/58.393858/24.645742
orphaned address cluster

## 102 Narva Maantee|24.797687,59.441815|https://www.openstreetmap.org/#map=16/59.441815/24.797687
orphaned address cluster (possibly two?)

## 3 Räpina Maantee|27.087538,58.080559|https://www.openstreetmap.org/#map=16/58.080559/27.087538
orphaned address cluster

## 19 äKsi Tee|26.666926,58.524105|https://www.openstreetmap.org/#map=16/58.524105/26.666926
orphaned address cluster

## 24 Päikese Tänav|27.280838,59.380453|https://www.openstreetmap.org/#map=16/59.380453/27.280838
orphaned address cluster

## 51 Vana-tartu Maantee|24.806662,59.389359|https://www.openstreetmap.org/#map=16/59.389359/24.806662
orphaned address cluster

## 6 Järve Põik|27.02713,57.795956|https://www.openstreetmap.org/#map=16/57.795956/27.02713
orphaned address cluster

# all-token mode failures

## 66 Oja Tänav|24.514933,58.395652|https://www.openstreetmap.org/#map=16/58.395652/24.514933
this is a straightforward assignment that shouldn't be failing. worrisome.

## 5 Oja Tänav|27.059448,58.053045|https://www.openstreetmap.org/#map=16/58.053045/27.059448
also failing when it should be a straightforward assignment. something's up with the all-token mode. 2808 Oja Tanav's are unassigned; 48 are assigned.

## 38 Puiestee Tänav|26.399217,58.743499|https://www.openstreetmap.org/#map=16/58.743499/26.399217
another seemingly straightforward assignment that operates under all-token mode
address_cluster id: 13411
network_cluster id: 6170

## 2 Puiestee Tänav|25.411551,58.809045|https://www.openstreetmap.org/#map=16/58.809045/25.411551
another seemingly straightforward assignment that operates under all-token mode
address_cluster id: 13415
network_cluster id: 6174

# missing OSM data

## 8 Kalda Tee|26.092391,58.666294|https://www.openstreetmap.org/#map=16/58.666294/26.092391
not mapped

## 122 Lääne Tänav|28.164226,59.349138|https://www.openstreetmap.org/#map=16/59.349138/28.164226
not mapped (or maybe mapped as `Lahe`)

## 3 Sepamardi Tee|24.873402,59.256046|https://www.openstreetmap.org/#map=16/59.256046/24.873402
not mapped

## 18 Põhja-pauli Tee|24.284363,59.349586|https://www.openstreetmap.org/#map=16/59.349586/24.284363
not mapped

## 7 Kuremäe Tee|24.263583,59.365295|https://www.openstreetmap.org/#map=16/59.365295/24.263583
not mapped

## 6 Rehe Tee|24.323094,59.286808|https://www.openstreetmap.org/#map=16/59.286808/24.323094
not mapped

## 9 Vana-madise Tee|24.361771,59.403702|https://www.openstreetmap.org/#map=16/59.403702/24.361771
not mapped

## 35 Tammiste Tee|24.591329,58.381397|https://www.openstreetmap.org/#map=16/58.381397/24.591329
not mapped -- appears to be the city name

## 10 Pootsmani Tee|24.710545,58.528994|https://www.openstreetmap.org/#map=16/58.528994/24.710545
not mapped

**Comment by sbma44** [comment]
OK, that was a simple fix: the algorithm was sound but it wasn't being fed the necessary fields from the database. Sometimes I wish Javascript had a `set -u` equivalent...

**Comment by sbma44** [comment]
Gotta hit 95 for a father's day observance, but I believe the following will handle the orphan address cluster case, if run after matching:

```sql
ALTER TABLE network_cluster ADD COLUMN address_text TEXT;
UPDATE network_CLUSTER n SET address_text=a._text FROM address_cluster a WHERE n.address = a.id;
ALTER TABLE address_cluster ADD COLUMN orphan_adoptive_parent BIGINT;
UPDATE address_cluster a SET orphan_adoptive_parent=n.address FROM network_cluster n WHERE a._text=n.address_text AND ST_Intersects(n.buffer, a.geom);
CREATE TABLE orphan_groups AS SELECT orphan_adoptive_parent, ST_CollectionExtract(ST_Collect(geom),1) AS geom FROM address_cluster GROUP BY orphan_adoptive_parent;
UPDATE address_cluster a SET geom=o.geom FROM orphan_groups o WHERE o.orphan_adoptive_parent=a.id;
DELETE FROM address_cluster WHERE id NOT IN (SELECT orphan_adoptive_parent FROM address_cluster WHERE orphan_adoptive_parent IS NOT NULL);
ALTER TABLE address_cluster DROP COLUMN orphan_adoptive_parent;
DROP TABLE orphan_groups;
```

I am pretty sure all of this could be collapsed down into a single ingenious SQL statement, but alas I am but a lowly craftsman.

**Comment by sbma44** [comment]
thinking about ^^^ it's conceivable that the action should be scoped to definitely-orphaned (unassigned) clusters. however the current logic takes every cluster as its own adoptee, which simplifies things a bit. I think this could only be a problem in circumstances where identically named ways have overlapping `buffer` boxes but are not joined into a single `network_cluster`. and even in that case I believe the resulting behavior would just be a nondeterministic assignment of the orphaned points to one or another of the clusters (which still might be bad, if it pulls them away from the correct one).

**Comment by sbma44** [comment]
compromise:

```sql
ALTER TABLE network_cluster ADD COLUMN address_text TEXT;
UPDATE network_CLUSTER n SET address_text=a._text FROM address_cluster a WHERE n.address = a.id;
ALTER TABLE address_cluster ADD COLUMN orphan_adoptive_parent BIGINT;
UPDATE address_cluster a SET orphan_adoptive_parent=n.address FROM network_cluster n WHERE (a._text=n.address_text AND ST_Intersects(n.buffer, a.geom) AND a.id NOT IN (SELECT address FROM network_cluster WHERE address IS NOT NULL)) OR (a.id=n.address);
CREATE TABLE orphan_groups AS SELECT orphan_adoptive_parent, ST_CollectionExtract(ST_Collect(geom),1) AS geom FROM address_cluster GROUP BY orphan_adoptive_parent;
UPDATE address_cluster a SET geom=o.geom FROM orphan_groups o WHERE o.orphan_adoptive_parent=a.id;
DELETE FROM address_cluster WHERE id NOT IN (SELECT orphan_adoptive_parent FROM address_cluster WHERE orphan_adoptive_parent IS NOT NULL);
ALTER TABLE address_cluster DROP COLUMN orphan_adoptive_parent;
DROP TABLE orphan_groups;
```

**Comment by sbma44** [comment]
This ticket spiraled out of control, but its initial impulse has been implemented in a few ways. Closing.
